name: Run

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dfetch
        run: pip install .

      - run: python -m dfetch validate
      - run: python -m dfetch check
      - run: python -m dfetch update
      - run: python -m dfetch check
