name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - run: isort --diff dfetch   # Checks import order
      - run: black --check dfetch  # Checks code style
      - run: flake8 dfetch         # Checks pep8 conformance
      - run: pylint dfetch         # Checks pep8 conformance
      - run: mypy --strict dfetch  # Check types
      - run: doc8 doc              # Checks documentation
      - run: pydocstyle dfetch     # Checks doc strings
